### ISSUE TITLE
Can I use request and response?

### ISSUE THREAD

**Issue by dhruvangg** [HubSpot/cms-event-registration#18]
Can I use req and res parameter for request and response in main.functions folder? 

Same as below: 

`exports.main = (req, res) => {
  res.json({ message: "Hello World" });
};`

Are context and sendResponse default parameter for export.main?

I want API call. Can I use axios here? Please provide reference or explained documentation.

**Comment by anthmatic** [comment]
@dhruvangg `context` and `sendResponse` are the 2 parameters that get passed to the function handler. You can see an example of how they're used here: https://designers.hubspot.com/features/serverless-functions/reference#function-file

The `request` library is available by default in functions. You can see an example of that in this repo: https://github.com/HubSpot/cms-event-registration/blob/master/src/event.functions/membership.js#L23

If you'd like to use `axios`, it is possible but you would need to bundle it into your function with something like webpack.

If you run into any other questions, I'd suggest joining the HubSpot developers Slack: https://designers.hubspot.com/slack
