### ISSUE TITLE
Remove calendar sidebar

### ISSUE THREAD

**Issue by anthmatic** [HubSpot/cms-event-registration#29]
Edit: per the convo below, let's just remove the calendar

Currently the calendar will visually display if there are events on a particular day, which isn't ideal. I'd suggest that selecting a day on the calendar should display all events on that day in a listing view. If it's not a terrible amount of work, It would also new nice to select a date range to view.

![image](https://user-images.githubusercontent.com/9009552/79382910-4b801900-7f32-11ea-9fe0-cc6a88ba5ce7.png)

cc @achong07 in case you have input on this

**Comment by achong07** [comment]
I'm wondering if the calendar view is really useful - I think it might be a better UX to remove the calendar altogether and add this as part of the filter.

A filter providing time frame options might be better:
- Today
- Tomorrow
- This week
- This month
- Next month
- This year

OR we could go about this simply by month + year:
- January 2020
- February 2020
- etc...

When I think about how I browse events, I'm usually not looking for a specific date unless I know the event that I'm looking for. Even then, I'd search for it other ways before I choose to search for it by the date. I'd usually use the date filter if I'm looking for things to do in the span of a certain time frame.

Any thoughts on this? @anthmatic @kemmerle @levinkeo

**Comment by anthmatic** [comment]
> When I think about how I browse events

@achong07 This is a really good point. Thinking about the use case for most customers (webinars and training?) maybe it makes sense to just remove the calendar for now?

If we do that, I do think we should add a way to filter between future and past events, though

**Comment by achong07** [comment]
I updated the mockups to demonstrate what it might look like without the calendar. Moved the "Log in" link, and added some options to the filter menu to represent the date. I think this will work, but I think it'd be great for people to be able to modify these time frames based on what makes sense for their use case.

https://hubspot.invisionapp.com/share/V8WK8447MXS#/414106746_Browse_By_Filter

**Comment by levinkeo** [comment]
I think I'm +1 for removing the calendar on the side for situations where there aren't tons of events. Thanks for mocking that up @achong07 !

In examples of portals with _lots_ of events, it might be interesting to think about what a calendar view might look like. As a user looking fo something like a concert, gym, or class schedule where there might be several events per week / day in the listing, I'm used to a pattern where I can flip through a monthly/weekly calendar interface.

**Comment by achong07** [comment]
@levinkeo would you be able to share some examples or instances of where you've found this useful? I'd like to explore this more!

There might be something to this - where the calendar is less about providing filter functionality, and is more about offering different view options. Maybe changing the way we think about the way content is arranged is warranted here, in this case, perhaps we are talking about exploring view options like:

- list
- cards/grid
- calendar

Kind of changes the perspective a little, and I see how something like that might be more useful than the current implementation.

**Comment by levinkeo** [comment]
@achong07 Yup! I'm sure there are plenty of other great examples, and unfortunately cancellations / postponements of most events make this a little difficult, but a few I was thinking of when I commented:

Classpass, ex. 
https://classpass.com/studios/barre-soul-harvard-square-cambridge?search-id=22467572634823689

Crossroads, ex.
http://events.crossroadspresents.com/venues/paradise-rock-club/month_events

Everybodyfights, ex.
https://www.everybodyfights.com/zingfit/#/schedule/site/1/wk/2

**Comment by anthmatic** [comment]
I agreed that a calendar view would be helpful, especially when there a large number of events to choose from. 

I still think that getting rid of the sidebar/filter calendar is the right move. And adding these views would make this pretty flexible:

>  - list
> - cards/grid
>  - calendar

**Comment by achong07** [comment]
Nice, so I think the right move right now is to remove the calendar on the side bar since that is designed to behave more like a filter. We can add some time frame filters to the filter functionality that's in the mocks to address this for now. Let me know if there's more that I can clarify there.

We can create a different issue to track adding different types of view options, including lists, cards/grids, and as a calendar.
