### ISSUE TITLE
Improve serverless endpoints

### ISSUE THREAD

**Issue by anthmatic** [HubSpot/cms-event-registration#41]
After working on #16, a few things stood out that might make sense to tackle:
- Change endpoint URLs:
  - `POST /registration/new` to `GET /auth`
  - `POST /registration` to `POST /register`
- We might want membership.js to return a 401 instead of 403 (pointed out by @levinkeo) https://github.com/HubSpot/cms-event-registration/blob/master/src/event.functions/membership.js#L15

I'm open to any feedback if folks don't think these changes make sense

**Comment by levinkeo** [comment]
I _think_ we'd want this the other way around, based on what we talked about offline @anthmatic , but please correct me if I'm wrong!
* So:
  * `POST /registration/new` becomes `POST /register`
  * `POST /registration` becomes `GET /auth`
