### ISSUE TITLE
Remove or rethink "join waitlist" state

### ISSUE THREAD

**Issue by levinkeo** [HubSpot/cms-event-registration#45]
When an event is full, we show a "join waitlist" button in place of a form that doesn't yet do anything. It's feasible to set up marketing automation to handle this, such as a form that submits to a property that's listened to by a dynamic list in the criteria of a workflow, but an out-of-the-box solution that doesn't require too much setup would take some additional thought. It might be interesting to have an example "recipe" for how to set this up.

In the interim we should replace this with a simple "this event is full" message.

**Comment by gcorne** [comment]
> In the interim we should replace this with a simple "this event is full" message.

I agree.
